server:
  port: 9080


#datasource#
spring:
  profiles:
    include: dev.prorperties
  datasource:
      url: jdbc:mysql://192.168.2.106:3306/manager_system?useUnicode=true&characterEncoding=utf-8
      username: manager
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapperLocations: classpath:mybatis/mapper/*.xml

#  typeAliasesPackage: com.blade.archetype.entity
#  config-location: classpath:mybatis/mybatis-config.xml

logging:
  config: classpath:log4j2.xml
